=== mernst/verigames/world.dtd
<!ELEMENT world (level*)>
 <!ELEMENT level (linked-edges,boards)>
  <!ATTLIST level name CDATA #REQUIRED>
  <!ELEMENT linked-edges (edge-set*)>
   <!ELEMENT edge-set (edgeref*)>
    <!ELEMENT edgeref EMPTY>
     <!ATTLIST edgeref id IDREF #REQUIRED>
  <!ELEMENT boards (board*)>
   <!ELEMENT board (node*,edge*)>
    <!ATTLIST board name ID #REQUIRED>
    <!ELEMENT node (input,output,layout?)>
     <!ATTLIST node kind (INCOMING|OUTGOING|SPLIT|NULL_TEST|MERGE|START_WHITE_BALL|START_BLACK_BALL|START_NO_BALL|END|SUBNETWORK|CONNECT) #REQUIRED>
     <!ATTLIST node id ID #REQUIRED>
     <!ATTLIST node name IDREF #IMPLIED>
     <!ELEMENT input (port*)>
     <!ELEMENT output (port*)>
      <!ELEMENT port EMPTY>
       <!ATTLIST port num CDATA #REQUIRED>
       <!ATTLIST port edge IDREF #REQUIRED>
     <!ELEMENT layout (x,y)>
      <!ELEMENT x (#PCDATA)>
      <!ELEMENT y (#PCDATA)>
    <!ELEMENT edge (from,to)>
     <!ATTLIST edge var CDATA #IMPLIED>
     <!ATTLIST edge pinch (true|false) #REQUIRED>
     <!ATTLIST edge width (wide|narrow) #REQUIRED>
     <!ATTLIST edge id ID #REQUIRED>
     <!ELEMENT from (noderef)>
     <!ELEMENT to (noderef)>
      <!ELEMENT noderef EMPTY>
       <!ATTLIST noderef id IDREF #REQUIRED>
       <!ATTLIST noderef port CDATA #REQUIRED>

<!--

Layout information:

   X and Y coordinates are integers starting at 0. (0,0) is the top left
   corner.

   Width:

      - MERGE, SPLIT, and NULL_TEST nodes have a width of 2. That is, a node to
      the right of a MERGE at (0,0) must be at (2,0) or to the right.

      - SUBNETWORK nodes have width = max(#incoming edges, #outgoing edges)

      - END nodes have a width of 1

   Height:

      - MERGE, SPLIT, START_XXX_BALL, and SUBNETWORK nodes have a height of 2.
      That is, a node below a SPLIT at (0,0) must be at (0,2) or below.

      - Nodes connected by an edge with pinch=true must have an extra y
      coordinate between them.

      - END nodes have a height of 1

Requirements not enforced by the DTD:

   - All edges are contained in exactly one edge-set

   - All nodes that have kind SUBNETWORK must have a name attribute

Misc:

   - NULL_TEST node:

      - Represents the branching that occurs when the variable represented by
      the input edge is tested against null.

      - Upon encountering this node, a small ball will roll to the output edge
      at port 0, and a large ball will roll to the output edge at port 1.

      - The output edge at port 0 must be narrow, and the output edge at port 1
      must be wide.
-->

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/SplitMergePractice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="SplitMerge" qid="17">
  <linked-edges>
   <edge-set id="SplitMergePractice1">
    <edgeref id="e1"/>
	<edgeref id="e11"/>
   </edge-set>
   <edge-set id="SplitMergePractice2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="SplitMergePractice3">
    <edgeref id="e3"/>
	<edgeref id="e33"/>
   </edge-set>
   <edge-set id="SplitMergePractice4">
    <edgeref id="e4"/>
   </edge-set>
   <edge-set id="SplitMergePractice5">
    <edgeref id="e5"/>
   </edge-set>
   <edge-set id="SplitMergePractice6">
    <edgeref id="e6"/>
   </edge-set>
   <edge-set id="SplitMergePractice7">
    <edgeref id="e7"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="SplitMergePractice--Board">
    <node kind="START_PIPE_DEPENDENT_BALL" id="n11">
     <input/>
     <output><port num="0" edge="e11"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="INCOMING" id="n33">
     <input/>
     <output><port num="0" edge="e33"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="INCOMING" id="n4">
     <input/>
     <output><port num="0" edge="e4"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="INCOMING" id="n5">
     <input/>
     <output><port num="0" edge="e5"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node id="n123" kind="MERGE">
     <input>
      <port edge="e1" num="left"/>
      <port edge="e2" num="right"/>
     </input>
     <output><port edge="e3" num="output"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node id="n367" kind="SPLIT">
     <input><port edge="e3" num="input"/></input>
     <output>
      <port edge="e6" num="output"/>
      <port edge="e7" num="split"/>
     </output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node id="n461" kind="MERGE">
     <input>
      <port edge="e4" num="left"/>
      <port edge="e6" num="right"/>
     </input>
     <output><port edge="e1" num="output"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node id="n572" kind="MERGE">
     <input>
      <port edge="e7" num="left"/>
      <port edge="e5" num="right"/>
     </input>
     <output><port edge="e2" num="output"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="OUTGOING" id="n110">
     <input><port num="0" edge="e11"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n330">
     <input><port num="0" edge="e33"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
	
    <edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e1" buzzsaw="false">
     <from><noderef id="n461" port="output"/></from>
     <to><noderef id="n123" port="left"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e11" buzzsaw="false">
     <from><noderef id="n11" port="0"/></from>
     <to><noderef id="n110" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e2" buzzsaw="false">
     <from><noderef id="n572" port="output"/></from>
     <to><noderef id="n123" port="right"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e3" buzzsaw="false">
     <from><noderef id="n123" port="output"/></from>
     <to><noderef id="n367" port="input"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e33" buzzsaw="false">
     <from><noderef id="n33" port="0"/></from>
     <to><noderef id="n330" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e4" buzzsaw="false">
     <from><noderef id="n4" port="0"/></from>
     <to><noderef id="n461" port="left"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e5" buzzsaw="false">
     <from><noderef id="n5" port="0"/></from>
     <to><noderef id="n572" port="right"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e6" buzzsaw="false">
     <from><noderef id="n367" port="output"/></from>
     <to><noderef id="n461" port="right"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e7" buzzsaw="false">
     <from><noderef id="n367" port="split"/></from>
     <to><noderef id="n572" port="left"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/SatisfyBoxes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Links" qid="4">
  <linked-edges>
   <edge-set id="SatisfyBoxes1">
    <edgeref id="e1"/>
   </edge-set>
   <edge-set id="SatisfyBoxes2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="SatisfyBoxes3">
    <edgeref id="e3"/>
    <edgeref id="e4"/>
   </edge-set>
   <edge-set id="SatisfyBoxes10">
    <edgeref id="e10"/>
   </edge-set>
   <edge-set id="SatisfyBoxes20">
    <edgeref id="e20"/>
   </edge-set>
   <edge-set id="SatisfyBoxes30">
    <edgeref id="e30"/>
   </edge-set>
   <edge-set id="SatisfyBoxes40">
    <edgeref id="e40"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="SatisfyBoxes--Board">
    <node kind="INCOMING" id="n1">
     <input/>
     <output>
      <port num="0" edge="e1"/>
	  <port num="1" edge="e3"/>
	  <port num="2" edge="e4"/>
     </output>
     <layout>
      <x>0.0</x>
      <y>0.0</y>
     </layout>
    </node>
	<node kind="START_SMALL_BALL" id="n2">
     <input/>
     <output>
      <port num="0" edge="e2"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n10">
     <input>
	  <port num="0" edge="e1"/>
	 </input>
     <output>
      <port num="0" edge="e10"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n20">
     <input>
	  <port num="0" edge="e2"/>
	 </input>
     <output>
      <port num="0" edge="e20"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n30">
     <input>
	  <port num="0" edge="e3"/>
	 </input>
     <output>
      <port num="0" edge="e30"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n40">
     <input>
	  <port num="0" edge="e4"/>
	 </input>
     <output>
      <port num="0" edge="e40"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n100">
     <input>
      <port num="0" edge="e10"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="OUTGOING" id="n200">
     <input>
      <port num="0" edge="e20"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n300">
     <input>
      <port num="0" edge="e30"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n400">
     <input>
      <port num="0" edge="e40"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e1" buzzsaw="false">
     <from>
      <noderef id="n1" port="0"/>
     </from>
     <to>
      <noderef id="n10" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e2" buzzsaw="false">
     <from>
      <noderef id="n2" port="0"/>
     </from>
     <to>
      <noderef id="n20" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e3" buzzsaw="false">
     <from>
      <noderef id="n1" port="1"/>
     </from>
     <to>
      <noderef id="n30" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e4" buzzsaw="false">
     <from>
      <noderef id="n1" port="2"/>
     </from>
     <to>
      <noderef id="n40" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e10" buzzsaw="false">
     <from>
      <noderef id="n10" port="0"/>
     </from>
     <to>
      <noderef id="n100" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e20" buzzsaw="false">
     <from>
      <noderef id="n20" port="0"/>
     </from>
     <to>
      <noderef id="n200" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e30" buzzsaw="false">
     <from>
      <noderef id="n30" port="0"/>
     </from>
     <to>
      <noderef id="n300" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e40" buzzsaw="false">
     <from>
      <noderef id="n40" port="0"/>
     </from>
     <to>
      <noderef id="n400" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/java/Translation/test/verigames/layout/GETLayoutTest.expected.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="GetTestLevel">
  <linked-edges>
   <edge-set id="GetTestLevel0">
    <edgeref id="e511"/>
   </edge-set>
   <edge-set id="GetTestLevel1">
    <edgeref id="e512"/>
   </edge-set>
   <edge-set id="GetTestLevel2">
    <edgeref id="e513"/>
   </edge-set>
   <edge-set id="GetTestLevel3">
    <edgeref id="e514"/>
   </edge-set>
   <edge-set id="GetTestLevel4">
    <edgeref id="e515"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="GetTestBoard">
    <node kind="INCOMING" id="n343">
     <input/>
     <output>
      <port num="0" edge="e511"/>
      <port num="1" edge="e512"/>
      <port num="2" edge="e513"/>
      <port num="3" edge="e514"/>
     </output>
     <layout>
      <x>0.00000</x>
      <y>0.00000</y>
     </layout>
    </node>
    <node kind="OUTGOING" id="n344">
     <input>
      <port num="0" edge="e515"/>
     </input>
     <output/>
     <layout>
      <x>0.00000</x>
      <y>7.68000</y>
     </layout>
    </node>
    <node kind="GET" id="n345">
     <input>
      <port num="0" edge="e511"/>
      <port num="1" edge="e512"/>
      <port num="2" edge="e513"/>
      <port num="3" edge="e514"/>
     </input>
     <output>
      <port num="0" edge="e515"/>
     </output>
     <layout>
      <x>0.00000</x>
      <y>2.02473</y>
     </layout>
    </node>
    <edge description="chute511" variableID="-1" pinch="false" width="narrow" editable="true" id="e511" buzzsaw="false">
     <from>
      <noderef id="n343" port="0"/>
     </from>
     <to>
      <noderef id="n345" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.50000</x>
       <y>0.00000</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>0.93871</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>1.15584</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>2.02473</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute512" variableID="-1" pinch="false" width="narrow" editable="true" id="e512" buzzsaw="false">
     <from>
      <noderef id="n343" port="1"/>
     </from>
     <to>
      <noderef id="n345" port="1"/>
     </to>
     <edge-layout>
      <point>
       <x>1.50000</x>
       <y>0.00000</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>0.93871</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>1.15584</y>
      </point>
      <point>
       <x>1.50000</x>
       <y>2.02473</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute513" variableID="-1" pinch="false" width="narrow" editable="true" id="e513" buzzsaw="false">
     <from>
      <noderef id="n343" port="2"/>
     </from>
     <to>
      <noderef id="n345" port="2"/>
     </to>
     <edge-layout>
      <point>
       <x>2.50000</x>
       <y>0.00000</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>0.93871</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>1.15584</y>
      </point>
      <point>
       <x>2.50000</x>
       <y>2.02473</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute514" variableID="-1" pinch="false" width="narrow" editable="true" id="e514" buzzsaw="false">
     <from>
      <noderef id="n343" port="3"/>
     </from>
     <to>
      <noderef id="n345" port="3"/>
     </to>
     <edge-layout>
      <point>
       <x>3.50000</x>
       <y>0.00000</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>0.93871</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>1.15584</y>
      </point>
      <point>
       <x>3.50000</x>
       <y>2.02473</y>
      </point>
     </edge-layout>
    </edge>
    <edge description="chute515" variableID="-1" pinch="false" width="narrow" editable="true" id="e515" buzzsaw="false">
     <from>
      <noderef id="n345" port="0"/>
     </from>
     <to>
      <noderef id="n344" port="0"/>
     </to>
     <edge-layout>
      <point>
       <x>0.50000</x>
       <y>3.48473</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>5.34938</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>5.81535</y>
      </point>
      <point>
       <x>0.50000</x>
       <y>7.68000</y>
      </point>
     </edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>
