=== mernst/verigames/world.dtd
<!ELEMENT world (level*)>
 <!ELEMENT level (linked-edges,boards)>
  <!ATTLIST level name CDATA #REQUIRED>
  <!ELEMENT linked-edges (edge-set*)>
   <!ELEMENT edge-set (edgeref*)>
    <!ELEMENT edgeref EMPTY>
     <!ATTLIST edgeref id IDREF #REQUIRED>
  <!ELEMENT boards (board*)>
   <!ELEMENT board (node*,edge*)>
    <!ATTLIST board name ID #REQUIRED>
    <!ELEMENT node (input,output,layout?)>
     <!ATTLIST node kind (INCOMING|OUTGOING|SPLIT|NULL_TEST|MERGE|START_WHITE_BALL|START_BLACK_BALL|START_NO_BALL|END|SUBNETWORK|CONNECT) #REQUIRED>
     <!ATTLIST node id ID #REQUIRED>
     <!ATTLIST node name IDREF #IMPLIED>
     <!ELEMENT input (port*)>
     <!ELEMENT output (port*)>
      <!ELEMENT port EMPTY>
       <!ATTLIST port num CDATA #REQUIRED>
       <!ATTLIST port edge IDREF #REQUIRED>
     <!ELEMENT layout (x,y)>
      <!ELEMENT x (#PCDATA)>
      <!ELEMENT y (#PCDATA)>
    <!ELEMENT edge (from,to)>
     <!ATTLIST edge var CDATA #IMPLIED>
     <!ATTLIST edge pinch (true|false) #REQUIRED>
     <!ATTLIST edge width (wide|narrow) #REQUIRED>
     <!ATTLIST edge id ID #REQUIRED>
     <!ELEMENT from (noderef)>
     <!ELEMENT to (noderef)>
      <!ELEMENT noderef EMPTY>
       <!ATTLIST noderef id IDREF #REQUIRED>
       <!ATTLIST noderef port CDATA #REQUIRED>

<!--

Layout information:

   X and Y coordinates are integers starting at 0. (0,0) is the top left
   corner.

   Width:

      - MERGE, SPLIT, and NULL_TEST nodes have a width of 2. That is, a node to
      the right of a MERGE at (0,0) must be at (2,0) or to the right.

      - SUBNETWORK nodes have width = max(#incoming edges, #outgoing edges)

      - END nodes have a width of 1

   Height:

      - MERGE, SPLIT, START_XXX_BALL, and SUBNETWORK nodes have a height of 2.
      That is, a node below a SPLIT at (0,0) must be at (0,2) or below.

      - Nodes connected by an edge with pinch=true must have an extra y
      coordinate between them.

      - END nodes have a height of 1

Requirements not enforced by the DTD:

   - All edges are contained in exactly one edge-set

   - All nodes that have kind SUBNETWORK must have a name attribute

Misc:

   - NULL_TEST node:

      - Represents the branching that occurs when the variable represented by
      the input edge is tested against null.

      - Upon encountering this node, a small ball will roll to the output edge
      at port 0, and a large ball will roll to the output edge at port 1.

      - The output edge at port 0 must be narrow, and the output edge at port 1
      must be wide.
-->

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Optimize.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Optimize">
  <linked-edges>
   <edge-set id="Optimize1">
    <edgeref id="e11"/>
	<edgeref id="e12"/>
   </edge-set>
   <edge-set id="Optimize2">
    <edgeref id="e21"/>
	<edgeref id="e22"/>
	<edgeref id="e23"/>
	<edgeref id="e24"/>
   </edge-set>
   <edge-set id="Optimize3">
    <edgeref id="e31"/>
	<edgeref id="e32"/>
	<edgeref id="e33"/>
	<edgeref id="e34"/>
	<edgeref id="e35"/>
   </edge-set>
   <edge-set id="Optimize4">
    <edgeref id="e41"/>
	<edgeref id="e42"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Optimize--Board">
    <node kind="INCOMING" id="n11">
     <input/>
     <output>
      <port num="0" edge="e11"/>
	  <port num="1" edge="e21"/>
	  <port num="2" edge="e31"/>
	  <port num="3" edge="e32"/>
	  <port num="4" edge="e41"/>
     </output>
     <layout>
      <x>0.0</x>
      <y>0.0</y>
     </layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n12">
     <input/>
     <output>
      <port num="0" edge="e12"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n23">
     <input/>
     <output>
      <port num="0" edge="e23"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n34">
     <input/>
     <output>
      <port num="0" edge="e34"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n42">
     <input/>
     <output>
      <port num="0" edge="e42"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n22">
     <input>
	  <port num="0" edge="e12"/>
	 </input>
     <output>
      <port num="0" edge="e22"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n24">
     <input>
	  <port num="0" edge="e34"/>
	 </input>
     <output>
      <port num="0" edge="e24"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n33">
     <input>
	  <port num="0" edge="e23"/>
	 </input>
     <output>
      <port num="0" edge="e33"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n35">
     <input>
	  <port num="0" edge="e42"/>
	 </input>
     <output>
      <port num="0" edge="e35"/>
     </output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n110">
     <input>
      <port num="0" edge="e11"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n210">
     <input>
      <port num="0" edge="e21"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n220">
     <input>
      <port num="0" edge="e22"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n240">
     <input>
      <port num="0" edge="e24"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n310">
     <input>
      <port num="0" edge="e31"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n320">
     <input>
      <port num="0" edge="e32"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n330">
     <input>
      <port num="0" edge="e33"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n350">
     <input>
      <port num="0" edge="e35"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n410">
     <input>
      <port num="0" edge="e41"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e11" buzzsaw="false">
     <from>
      <noderef id="n11" port="0"/>
     </from>
     <to>
      <noderef id="n110" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e12" buzzsaw="false">
     <from>
      <noderef id="n12" port="0"/>
     </from>
     <to>
      <noderef id="n22" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e21" buzzsaw="false">
     <from>
      <noderef id="n11" port="1"/>
     </from>
     <to>
      <noderef id="n210" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e22" buzzsaw="false">
     <from>
      <noderef id="n22" port="0"/>
     </from>
     <to>
      <noderef id="n220" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e23" buzzsaw="false">
     <from>
      <noderef id="n23" port="0"/>
     </from>
     <to>
      <noderef id="n33" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e24" buzzsaw="false">
     <from>
      <noderef id="n24" port="0"/>
     </from>
     <to>
      <noderef id="n240" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e31" buzzsaw="false">
     <from>
      <noderef id="n11" port="2"/>
     </from>
     <to>
      <noderef id="n310" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e32" buzzsaw="false">
     <from>
      <noderef id="n11" port="3"/>
     </from>
     <to>
      <noderef id="n320" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="true" width="narrow" editable="true" id="e33" buzzsaw="false">
     <from>
      <noderef id="n33" port="0"/>
     </from>
     <to>
      <noderef id="n330" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e34" buzzsaw="false">
     <from>
      <noderef id="n34" port="0"/>
     </from>
     <to>
      <noderef id="n24" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="true" width="narrow" editable="true" id="e35" buzzsaw="false">
     <from>
      <noderef id="n35" port="0"/>
     </from>
     <to>
      <noderef id="n350" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e41" buzzsaw="false">
     <from>
      <noderef id="n11" port="4"/>
     </from>
     <to>
      <noderef id="n410" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e42" buzzsaw="false">
     <from>
      <noderef id="n42" port="0"/>
     </from>
     <to>
      <noderef id="n35" port="0"/>
     </to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Layout" qid="12">
  <linked-edges>
   <edge-set id="Layout1">
    <edgeref id="e1"/>
   </edge-set>
   <edge-set id="Layout2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="Layout3">
    <edgeref id="e3"/>
   </edge-set>
   <edge-set id="Layout4">
    <edgeref id="e4"/>
   </edge-set>
   <edge-set id="Layout5">
    <edgeref id="e5"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Layout--Board">
    <node kind="INCOMING" id="n1">
     <input/>
     <output><port num="0" edge="e1"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n2">
     <input/>
     <output><port num="0" edge="e2"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n3">
     <input/>
     <output><port num="0" edge="e3"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n4">
     <input/>
     <output><port num="0" edge="e4"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n5">
     <input/>
     <output><port num="0" edge="e5"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n10">
     <input><port num="0" edge="e1"/></input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n20">
     <input><port num="0" edge="e2"/></input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n30">
     <input><port num="0" edge="e3"/></input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="OUTGOING" id="n40">
     <input><port num="0" edge="e4"/></input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n50">
     <input><port num="0" edge="e5"/></input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e1" buzzsaw="false">
     <from><noderef id="n1" port="0"/></from>
     <to><noderef id="n10" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e2" buzzsaw="false">
     <from><noderef id="n2" port="0"/></from>
     <to><noderef id="n20" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e3" buzzsaw="false">
     <from><noderef id="n3" port="0"/></from>
     <to><noderef id="n30" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e4" buzzsaw="false">
     <from><noderef id="n4" port="0"/></from>
     <to><noderef id="n40" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e5" buzzsaw="false">
     <from><noderef id="n5" port="0"/></from>
     <to><noderef id="n50" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Merges.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Merges">
  <linked-edges>
   <edge-set id="Merges1">
    <edgeref id="e1"/>
   </edge-set>
   <edge-set id="Merges2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="Merges3">
    <edgeref id="e3"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Merges--Board">
    <node kind="START_PIPE_DEPENDENT_BALL" id="n1">
     <input/>
     <output><port num="0" edge="e1"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n2">
     <input/>
     <output><port num="0" edge="e2"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
    <node id="n123" kind="MERGE">
     <input>
      <port edge="e1" num="left"/>
      <port edge="e2" num="right"/>
     </input>
     <output><port edge="e3" num="output"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n3">
     <input><port num="0" edge="e3"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e1" buzzsaw="false">
     <from><noderef id="n1" port="0"/></from>
     <to><noderef id="n123" port="left"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e2" buzzsaw="false">
     <from><noderef id="n2" port="0"/></from>
     <to><noderef id="n123" port="right"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e3" buzzsaw="false">
     <from><noderef id="n123" port="output"/></from>
     <to><noderef id="n3" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Passages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Passages">
  <linked-edges>
   <edge-set id="Passages2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="Passages3">
	<edgeref id="e32"/>
	<edgeref id="e33"/>
   </edge-set>
   <edge-set id="Passages4">
    <edgeref id="e42"/>
   </edge-set>
   <edge-set id="Passages5">
    <edgeref id="e53"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Passages--Board">
	<node kind="START_LARGE_BALL" id="n2">
     <input/>
     <output>
      <port num="0" edge="e2"/>
     </output>
     <layout>
      <x>0.0</x>
      <y>0.0</y>
     </layout>
    </node>
	<node kind="START_PIPE_DEPENDENT_BALL" id="n3">
     <input/>
     <output>
      <port num="0" edge="e33"/>
     </output>
     <layout>
      <x>0.0</x>
      <y>0.0</y>
     </layout>
    </node>
	<node kind="CONNECT" id="n23">
     <input><port num="0" edge="e2"/></input>
     <output><port num="0" edge="e32"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n342">
     <input><port num="0" edge="e32"/></input>
     <output><port num="0" edge="e42"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="CONNECT" id="n353">
     <input><port num="0" edge="e33"/></input>
     <output><port num="0" edge="e53"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n420">
     <input>
      <port num="0" edge="e42"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n530">
     <input>
      <port num="0" edge="e53"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e2" buzzsaw="false">
     <from><noderef id="n2" port="0"/></from>
     <to><noderef id="n23" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e32" buzzsaw="false">
     <from><noderef id="n23" port="0"/></from>
     <to><noderef id="n342" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e33" buzzsaw="false">
     <from><noderef id="n3" port="0"/></from>
     <to><noderef id="n353" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e42" buzzsaw="false">
     <from><noderef id="n342" port="0"/></from>
     <to><noderef id="n420" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e53" buzzsaw="false">
     <from><noderef id="n353" port="0"/></from>
     <to><noderef id="n530" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Splits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Splits" qid="10">
  <linked-edges>
   <edge-set id="Splits1">
    <edgeref id="e1"/>
   </edge-set>
   <edge-set id="Splits2">
    <edgeref id="e2"/>
   </edge-set>
   <edge-set id="Splits3">
    <edgeref id="e3"/>
   </edge-set>
   <edge-set id="Splits4">
    <edgeref id="e4"/>
   </edge-set>
   <edge-set id="Splits5">
    <edgeref id="e5"/>
   </edge-set>
   <edge-set id="Splits6">
    <edgeref id="e6"/>
   </edge-set>
  </linked-edges>
  <boards>
    <board name="Splits--Sub">
    <node kind="START_PIPE_DEPENDENT_BALL" id="n1">
     <input/>
     <output><port num="0" edge="e1"/></output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="OUTGOING" id="n10">
     <input><port num="0" edge="e1"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e1" buzzsaw="false">
     <from><noderef id="n1" port="0"/></from>
     <to><noderef id="n10" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
   <board name="Splits--Board">
    <node id="n2" kind="SUBBOARD" name="Splits--Sub">
     <input/>
     <output>
      <port edge="e2" num="0"/>
     </output>
     <layout><x>0</x><y>0</y>
     </layout>
    </node>
	<node id="n3" kind="SUBBOARD" name="Splits--Sub">
     <input/>
     <output>
      <port edge="e3" num="0"/>
     </output>
     <layout><x>0</x><y>0</y>
     </layout>
    </node>
	<node id="n4" kind="SUBBOARD" name="Splits--Sub">
     <input/>
     <output>
      <port edge="e4" num="0"/>
     </output>
     <layout><x>0</x><y>0</y>
     </layout>
    </node>
	<node id="n40" kind="SPLIT">
     <input><port edge="e4" num="input"/></input>
     <output>
      <port edge="e5" num="output"/>
      <port edge="e6" num="split"/>
     </output>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n20">
     <input><port num="0" edge="e2"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n30">
     <input><port num="0" edge="e3"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n50">
     <input><port num="0" edge="e5"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
	<node kind="END" id="n60">
     <input><port num="0" edge="e6"/></input>
     <output/>
     <layout><x>0</x><y>0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e2" buzzsaw="false">
     <from><noderef id="n2" port="0"/></from>
     <to><noderef id="n20" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e3" buzzsaw="false">
     <from><noderef id="n3" port="0"/></from>
     <to><noderef id="n30" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="true" id="e4" buzzsaw="false">
     <from><noderef id="n4" port="0"/></from>
     <to><noderef id="n40" port="input"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="wide" editable="false" id="e5" buzzsaw="false">
     <from><noderef id="n40" port="output"/></from>
     <to><noderef id="n50" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e6" buzzsaw="false">
     <from><noderef id="n40" port="split"/></from>
     <to><noderef id="n60" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>

=== mernst/verigames/flash/PipeJam3/lib/levels/tutorial/setup/Clashes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "world.dtd">
<world version="1">
 <level name="Jams" qid="6">
  <linked-edges>
   <edge-set id="Clashes1">
    <edgeref id="e1"/>
   </edge-set>
   <edge-set id="Clashes2">
    <edgeref id="e2"/>
   </edge-set>
  </linked-edges>
  <boards>
   <board name="Clashes--Board">
    <node kind="START_PIPE_DEPENDENT_BALL" id="n1">
     <input/>
     <output>
      <port num="0" edge="e1"/>
     </output>
     <layout>
      <x>0.0</x>
      <y>0.0</y>
     </layout>
    </node>
	<node kind="CONNECT" id="n12">
     <input><port num="0" edge="e1"/></input>
     <output><port num="0" edge="e2"/></output>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
	<node kind="END" id="n2">
     <input>
      <port num="0" edge="e2"/>
     </input>
     <output/>
     <layout><x>0.0</x><y>0.0</y></layout>
    </node>
    <edge description="this" variableID="-1" pinch="false" width="wide" editable="true" id="e1" buzzsaw="false">
     <from><noderef id="n1" port="0"/></from>
     <to><noderef id="n12" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
	<edge description="this" variableID="-1" pinch="false" width="narrow" editable="false" id="e2" buzzsaw="false">
     <from><noderef id="n12" port="0"/></from>
     <to><noderef id="n2" port="0"/></to>
     <edge-layout><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point><point><x>0</x><y>0</y></point></edge-layout>
    </edge>
   </board>
  </boards>
 </level>
</world>
